# Generated by Django 2.0.1 on 2018-02-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='company_ticker',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
