# Generated by Django 2.0.1 on 2018-02-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20180221_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquerydata',
            old_name='user_id',
            new_name='user',
        ),
    ]
